version: '3'

services:
  server1:
    build: ./shared
    image: server
    ports:
      - '8090'
    command:
      - '8090'
  server2:
    build: ./shared
    image: server
    ports:
      - '8091'
    command:
      - '8091'
  server3:
    build: ./shared
    image: server
      - '8092'
    command:
      - '8092'

  l4lb-cpp:
    build: ./cpp
    image: l4lb-cpp
    privileged: true
    cap_add:
      - NET_RAW
    ports:
      - '20000:20000'
    command:
      - '0.0.0.0'
      - 'server1'
      - '8090'
      - 'server2'
      - '8091'
      - 'server3'
      - '8092'
    depends_on:
      - server1
      - server2
      - server3
